DROP TABLE vbvscs;
CREATE TABLE vbvscs (
	id INT IDENTITY PRIMARY KEY,
	url NVARCHAR(450) NOT NULL UNIQUE,
	salary MONEY NOT NULL CHECK(salary > 0),
	username CHAR(11) NOT NULL,
	created DATETIME DEFAULT GETDATE()
);
